//browser API key bi Google
var developerKey = 'AIzaSyA9tHLQWsdSXjzpvuL5AALWosKqQ0UW9eY'	

//client ID (oAuth generated by Google)

var clientId = '837398770659-ohpoarigpidhhplnmfghc2cffkjuf3ab.apps.googleusercontent.com'

var scope = ['https://www.googleapis.com/auth/photos']

var pickerApiLoaded = false;

var oauthToken;

// API Laoder to load google.picker and gapi.auth per https://developers.google.com/picker/docs/

function onApiLoad(){

	gapi.load('auth', {'callback' : onAuthApiLoad});
	gapi.load('picker', {'callback' : onPickerApiLoad});
}

function onAuthApiLoad() {
  window.gapi.auth.authorize(
  	{
      'client_id': clientId,
      'scope': scope,
      'immediate': false
    },
    handleAuthResult);
}

function onPickerApiLoad(){
	pickerApiLoaded = true;
	createPicker();
}

function handleAuthResult (authResult) {
	if(authResult && !authResult.error){
		oauthToken = authResult.access_token;
		createPicker();
	}
}

//Picker Object rendering user photos right now

function createPicker(){
	if(pickerApiLoaded && oauthToken){
		var picker = new google.picker.PickerBuilder()
				.addView(google.picker.ViewId.PHOTOS)
				.setOAuthToken(oauthToken)
				.setDeveloperKey(developerKey)
				.setCallback(pickerCallback)
				.build();
			picker.setVisible(true);
	}
}

function pickerCallback (data) {
	var url = 'nothing';
	if (data[google.picker.Response.ACTION] == google.picker.Action.PICKED) {
		var doc = data[google.picker.Response.DOCUMENTS][0];
		url = doc[google.picker.Document.URL];
	}
	var message = 'You picked: ' + url;
	document.getElementById('result').innerHTML = message;
}